import { serve } from "https://deno.land/std@0.168.0/http/server.ts";
import { createClient } from "https://esm.sh/@supabase/supabase-js@2";

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers": "authorization, x-client-info, apikey, content-type, x-supabase-client-platform, x-supabase-client-platform-version, x-supabase-client-runtime, x-supabase-client-runtime-version",
};

serve(async (req) => {
  if (req.method === "OPTIONS") return new Response(null, { headers: corsHeaders });

  try {
    const { sceneId, projectId } = await req.json();
    
    const LOVABLE_API_KEY = Deno.env.get("LOVABLE_API_KEY");
    if (!LOVABLE_API_KEY) throw new Error("LOVABLE_API_KEY not configured");

    const supabaseUrl = Deno.env.get("SUPABASE_URL")!;
    const supabaseKey = Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!;
    const supabase = createClient(supabaseUrl, supabaseKey);

    // Get scene data
    const { data: scene, error: sceneErr } = await supabase
      .from("scenes")
      .select("*")
      .eq("id", sceneId)
      .single();

    if (sceneErr || !scene) throw new Error("Scene not found");

    // Get project data for context
    const { data: project } = await supabase
      .from("projects")
      .select("*")
      .eq("id", projectId)
      .single();

    // Update status to generating
    await supabase.from("scenes").update({ status: "generating" }).eq("id", sceneId);

    // Get previous scene image for reference
    let referenceContext = "";
    if (scene.scene_number > 1) {
      const { data: prevScene } = await supabase
        .from("scenes")
        .select("output_image_url, scene_title")
        .eq("project_id", projectId)
        .eq("scene_number", scene.scene_number - 1)
        .single();
      
      if (prevScene?.output_image_url) {
        referenceContext = `This is scene ${scene.scene_number} continuing from "${prevScene.scene_title}". Maintain visual continuity with the previous scene.`;
      }
    }

    // Generate image using Lovable AI with image generation model
    const imagePrompt = `${scene.image_prompt}\n\n${referenceContext}\n\nProject context: ${project?.selected_idea}, style: ${project?.final_style}, mood: ${project?.visual_mood}. Create a photorealistic, cinematic 16:9 image.`;

    const messages: any[] = [
      { role: "user", content: imagePrompt }
    ];

    // If there's a previous scene image, include it for visual continuity
    if (scene.scene_number > 1) {
      const { data: prevScene } = await supabase
        .from("scenes")
        .select("output_image_url")
        .eq("project_id", projectId)
        .eq("scene_number", scene.scene_number - 1)
        .single();

      if (prevScene?.output_image_url) {
        messages[0] = {
          role: "user",
          content: [
            { type: "text", text: `Based on the reference image from the previous scene, generate the next scene. ${imagePrompt}` },
            { type: "image_url", image_url: { url: prevScene.output_image_url } }
          ]
        };
      }
    }

    const response = await fetch("https://ai.gateway.lovable.dev/v1/chat/completions", {
      method: "POST",
      headers: {
        Authorization: `Bearer ${LOVABLE_API_KEY}`,
        "Content-Type": "application/json",
      },
      body: JSON.stringify({
        model: "google/gemini-2.5-flash-image",
        messages,
        modalities: ["image", "text"],
      }),
    });

    if (!response.ok) {
      const errText = await response.text();
      console.error("AI image error:", response.status, errText);
      await supabase.from("scenes").update({ status: "failed" }).eq("id", sceneId);
      
      if (response.status === 429) {
        return new Response(JSON.stringify({ error: "Rate limit exceeded. Please wait and try again." }), {
          status: 429, headers: { ...corsHeaders, "Content-Type": "application/json" },
        });
      }
      if (response.status === 402) {
        return new Response(JSON.stringify({ error: "AI credits exhausted." }), {
          status: 402, headers: { ...corsHeaders, "Content-Type": "application/json" },
        });
      }
      throw new Error(`AI image generation failed: ${response.status}`);
    }

    const data = await response.json();
    const imageData = data.choices?.[0]?.message?.images?.[0]?.image_url?.url;

    if (!imageData) {
      await supabase.from("scenes").update({ status: "failed" }).eq("id", sceneId);
      throw new Error("No image generated by AI");
    }

    // Upload base64 image to storage
    const base64Data = imageData.replace(/^data:image\/\w+;base64,/, "");
    const imageBytes = Uint8Array.from(atob(base64Data), (c) => c.charCodeAt(0));
    
    const filePath = `${projectId}/scenes/scene_${scene.scene_number}.png`;
    const { error: uploadErr } = await supabase.storage
      .from("project-assets")
      .upload(filePath, imageBytes, {
        contentType: "image/png",
        upsert: true,
      });

    if (uploadErr) {
      console.error("Upload error:", uploadErr);
      await supabase.from("scenes").update({ status: "failed" }).eq("id", sceneId);
      throw uploadErr;
    }

    const { data: publicUrl } = supabase.storage
      .from("project-assets")
      .getPublicUrl(filePath);

    // Update scene with image URL
    const { data: updatedScene, error: updateErr } = await supabase
      .from("scenes")
      .update({
        output_image_url: publicUrl.publicUrl,
        status: "completed",
      })
      .eq("id", sceneId)
      .select()
      .single();

    if (updateErr) throw updateErr;

    // Also update the next scene's reference image
    await supabase
      .from("scenes")
      .update({ reference_image_url: publicUrl.publicUrl })
      .eq("project_id", projectId)
      .eq("scene_number", scene.scene_number + 1);

    // Update transition start/end images
    await supabase
      .from("transitions")
      .update({ end_image_url: publicUrl.publicUrl })
      .eq("project_id", projectId)
      .eq("from_scene", scene.scene_number);

    await supabase
      .from("transitions")
      .update({ start_image_url: publicUrl.publicUrl })
      .eq("project_id", projectId)
      .eq("to_scene", scene.scene_number);

    return new Response(JSON.stringify({ scene: updatedScene }), {
      headers: { ...corsHeaders, "Content-Type": "application/json" },
    });
  } catch (e) {
    console.error("generate-scene-image error:", e);
    return new Response(JSON.stringify({ error: e instanceof Error ? e.message : "Unknown error" }), {
      status: 500, headers: { ...corsHeaders, "Content-Type": "application/json" },
    });
  }
});
